<a href="https://colab.research.google.com/github/basselkassem/easy21/blob/master/game_config.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Episodes number

In [2]:
EPISODES_NUMS = np.array([10**2, 10**3, 10**4,10**5])
print(EPISODES_NUMS)

[100, 1000, 10000, 100000]


# Maximum score to lose

In [0]:
MAX_VALUE = 21

# Minimum score to lose

In [0]:
MIN_VALUE = 1

# Maximum of the cards values

In [0]:
CARD_VALUE_MAX = 10

# Minimum of the cards values

In [0]:
CARD_VALUE_MIN = 1

# Maximum score for dealer to stick

In [0]:
DEALER_THRESHOLD = 17

# Action space

In [15]:
HIT = 0
STICK = 1
ACTION_SPACE = np.array([HIT, STICK])
print(ACTION_SPACE)

[0 1]


# State Space
The **state** is represented as a 2D array
*   rows represent the dealer first card
*   columns represent the player's score



In [8]:
DEALER_FIRST_CARD_SPACE = np.arange(CARD_VALUE_MIN, CARD_VALUE_MAX + 1)
print(DEALER_FIRST_CARD_SPACE, DEALER_FIRST_CARD_SPACE.shape )
PLAYER_SOCRE = np.arange(MIN_VALUE, MAX_VALUE + 1)
print(PLAYER_SOCRE, PLAYER_SOCRE.shape)
STATE_SPACE_SHAPE = (len(DEALER_FIRST_CARD_SPACE), len(PLAYER_SOCRE),)
print(STATE_SPACE_SHAPE)

[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] (21,)
(10, 21)


# Action-State Space
The **Action-State** is represented as a 3D array


*   1th-D represents the dealer first card
*   2nd-D represent the player's score
*   3th-D represent the action



    
    


In [9]:
ACTION_STATE_SPACE_SHAPE = (len(DEALER_FIRST_CARD_SPACE), len(PLAYER_SOCRE), len(ACTION_SPACE))
print(ACTION_STATE_SPACE_SHAPE)

(10, 21, 2)


# Epsilon greedy constant

In [12]:
N0_VALUES = np.array([50, 100, 1000])
print(N0_VALUES)

[  50  100 1000]
